### ISSUE TITLE
IS there a way to turn off discriminator training?

### ISSUE THREAD

**Issue by Suvi-dha** [barisgecer/TBGAN#11]

**Comment by Suvi-dha** [comment]
I am getting this error when training to train just shape maps using your pretrained network.  And I don't have labels in my training data.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 638, in set_shape
    c_api.TF_GraphSetTensorShape_wrapper(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 0 and 7. Shapes are [?,0] and [?,7].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 290, in <module>
    tfutil.call_func_by_name(**config.train)
  File "/root/TBGAN/tfutil.py", line 234, in call_func_by_name
    return import_obj(func)(*args, **kwargs)
  File "/root/TBGAN/train.py", line 189, in train_progressive_gan
    G_loss = tfutil.call_func_by_name(G=G_gpu, D=D_gpu, opt=G_opt, training_set=training_set, minibatch_size=minibatch_split, **config.G_loss)
  File "/root/TBGAN/tfutil.py", line 234, in call_func_by_name
    return import_obj(func)(*args, **kwargs)
  File "/root/TBGAN/loss.py", line 30, in G_wgan_acgan
    fake_images_out = G.get_output_for(latents, labels, is_training=True)
  File "/root/TBGAN/tfutil.py", line 507, in get_output_for
    out_expr = self._build_func(*named_inputs, **all_kwargs)
  File "<string>", line 175, in G_paper
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py", line 645, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 0 and 7. Shapes are [?,0] and [?,7].`

**Comment by rohit7044** [comment]
Hey @Suvi-dha ! 
Can you tell me how you manged to get the training dataset ready?

**Comment by Suvi-dha** [comment]
Hi @rohit7044  I have few 3D models with their textures. I converted those 3D models to shape maps and normals.

**Comment by rohit7044** [comment]
But the input says modalities. What does modalities mean ? I am so confused.
Given multi-view images as input I am trying to understand if TB-GAN can generate normal and UV map. Can you share your opinion?
